fastlane_version "2.68.2"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload Backable Fragment Protocol"
  lane :release_backable_fragment do
    deploy_module_bintray(module_name: "protocol-backable-fragment", should_clean: true)
  end

  desc "Upload Date Formatter Protocol"
  lane :release_date_formatter do
    deploy_module_bintray(module_name: "protocol-date-formatter", should_clean: true)
  end

  desc "Upload Disposer Protocol"
  lane :release_disposer do
    deploy_module_bintray(module_name: "protocol-rx-disposer", should_clean: true)
  end

  desc "Upload Message Presenter Protocol"
  lane :release_message_presenter do
    deploy_module_bintray(module_name: "protocol-message-presenter", should_clean: true)
  end

  desc "Deploy all libs to maven"
  lane :deploy do
    deploy_module_bintray(module_name: "protocol-backable-fragment", should_clean: true)
    deploy_module_bintray(module_name: "protocol-date-formatter")
    deploy_module_bintray(module_name: "protocol-rx-disposer")
    deploy_module_bintray(module_name: "protocol-message-presenter")
  end
end
